project_id = "epgifclglrrgzpguqbde"

[functions.invite-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.get-users-with-status]
verify_jwt = true

[functions.toggle-user-status]
verify_jwt = true

[functions.update-user]
verify_jwt = true

[functions.send-collection-emails]
verify_jwt = false

[functions.send-billing-emails]
verify_jwt = false

[functions.cnpj-lookup]
verify_jwt = false

[functions.analyze-dre-simulation]
verify_jwt = false
